ci: removed for test purposes

diff --git a/.github/workflows/webapp-e2e-tests-on-demand.yml b/.github/workflows/webapp-e2e-tests-on-demand.yml
--- a/.github/workflows/webapp-e2e-tests-on-demand.yml
+++ b/.github/workflows/webapp-e2e-tests-on-demand.yml
@@ -21,20 +21,22 @@ jobs:
     outputs:
       base: ${{ steps.detect-base.outputs.base }}
     steps:
-      - name: Check if branch exists
-        run: |
-          echo "Checking if branch '${{ github.event.inputs.branch }}' exists..."
-          branch_name="${{ github.event.inputs.branch }}"
-          branch_check=$(curl -s -o /dev/null -w "%{http_code}" \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            https://api.github.com/repos/${{ github.repository }}/branches/$branch_name)
-          if [[ "$branch_check" != "200" ]]; then
-            echo "Error: Branch '$branch_name' does not exist (HTTP $branch_check)."
-            exit 1
-          fi
-          echo "Branch '$branch_name' exists."
-
-      - uses: actions/checkout@v4
+#      - name: Check if branch exists
+#        run: |
+#          echo "Checking if branch '${{ github.event.inputs.branch }}' exists..."
+#          branch_name="${{ github.event.inputs.branch }}"
+#          branch_check=$(curl -s -o /dev/null -w "%{http_code}" \
+#            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+#            https://api.github.com/repos/${{ github.repository }}/branches/$branch_name)
+#          if [[ "$branch_check" != "200" ]]; then
+#            echo "Error: Branch '$branch_name' does not exist (HTTP $branch_check)."
+#            exit 1
+#          fi
+#          echo "Branch '$branch_name' exists."
+#
+#      - uses: actions/checkout@v4
+      - name: Check out repository code
+        uses: actions/checkout@v4
 
       - name: Detect base branch
         id: detect-base
